In [1]:
import requests
import xmltodict
import pprint
import json

In [2]:
url = "https://bps.quickbase.com/db/bqsuve7qy?a=API_DoQuery&fmt=structured&usertoken=b5d3bm_kn5b_d4c4hh5b76ajm4t6fzg96bbber"
#url = "https://builderprogram-pverma.quickbase.com/db/bqscz87a5?a=API_DoQuery&fmt=structured&ticket=9_bqs7bdfax_b5fdma_nx3z_a_-b_ufsj4vbstivafsmxsfcdxq9mdbckgwuzxb8r9rk9bvnwt8ebi7agah_d2re5rt"

In [3]:
url

'https://bps.quickbase.com/db/bqsuve7qy?a=API_DoQuery&fmt=structured&usertoken=b5d3bm_kn5b_d4c4hh5b76ajm4t6fzg96bbber'

In [4]:
response = requests.request("GET", url)
print(response)
r=response.text.encode('utf8')
print(r)
pp = pprint.PrettyPrinter(indent=4)
data=json.dumps(xmltodict.parse(r))
data1=json.loads(data)

<Response [200]>
b'<?xml version="1.0" ?>\r\n<qdbapi>\n\t<action>API_DoQuery</action>\r\n\t<errcode>0</errcode>\r\n\t<errtext>No error</errtext>\r\n    <qid>-1</qid>\r\n    <qname></qname>\r\n    <table>\r\n      <name>Track Record Documents</name>\r\n      <original>\r\n        <table_id>bqsuve7qy</table_id>\r\n\t\t <app_id>bpqjjg28h</app_id>\r\n        <cre_date>1598351898050</cre_date>\r\n        <mod_date>1599656949691</mod_date>\r\n        <next_record_id>4</next_record_id>\r\n        <next_field_id>9</next_field_id>\r\n        <next_query_id>5</next_query_id>\r\n        <def_sort_fid>2</def_sort_fid>\r\n        <def_sort_order>0</def_sort_order>\r\n    <key_fid>3</key_fid>\r\n        <single_record_name>Track Record Document</single_record_name>\r\n        <plural_record_name>Track record documents</plural_record_name>\r\n      </original>\r\n      <variables>\r\n        <var name="appID">bpqjjg28h</var>\r\n        <var name="SecretKey">cIYauNev61s.KYXLMcY9yATi9z9_OOTzlPp9LkVsYKA610syho2Yb4Y</var>\r\n        <var name="tblUserPreferenceList">bpq27dt3d</var>\r\n      </variables>\r\n      <queries>\r\n        <query id="1">\r\n          <qyname>List All</qyname>\r\n          <qytype>table</qytype>\r\n          <qyopts>nos.qws.</qyopts>\r\n\t\t  <qycalst>0.0</qycalst>\r\n        </query>\r\n        <query id="2">\r\n          <qyname>List Changes</qyname>\r\n          <qytype>table</qytype>\r\n          <qydesc>Sorted by Date Modified</qydesc>\r\n          <qyslst>2</qyslst>\r\n          <qyopts>so-D.onlynew.nos.qws.</qyopts>\r\n\t\t  <qycalst>0.0</qycalst>\r\n        </query>\r\n      </queries>\r\n      <fields>\r\n        <field id="3" field_type="recordid" base_type="int32" role="recordid" mode="virtual">\r\n          <label>Record ID#</label>\n          <nowrap>1</nowrap>\n          <bold>0</bold>\n          <required>0</required>\n          <appears_by_default>1</appears_by_default>\n          <find_enabled>0</find_enabled>\n          <allow_new_choices>0</allow_new_choices>\n          <sort_as_given>1</sort_as_given>\n          <carrychoices>1</carrychoices>\n          <foreignkey>0</foreignkey>\n          <unique>1</unique>\n          <doesdatacopy>0</doesdatacopy>\n          <fieldhelp></fieldhelp>\n          <audited>0</audited>\n          <decimal_places>0</decimal_places>\n\t\t  <comma_start>4</comma_start>\n\t\t  <numberfmt>0</numberfmt>\n          <does_average>0</does_average>\n          <does_total>0</does_total>\n          <blank_is_zero>1</blank_is_zero>\n        </field>\r\n        <field id="6" field_type="text" base_type="text">\r\n          <label>Title</label>\n          <nowrap>0</nowrap>\n          <bold>0</bold>\n          <required>0</required>\n          <appears_by_default>1</appears_by_default>\n          <find_enabled>1</find_enabled>\n          <allow_new_choices>0</allow_new_choices>\n          <sort_as_given>1</sort_as_given>\n          <carrychoices>1</carrychoices>\n          <foreignkey>0</foreignkey>\n          <unique>0</unique>\n          <doesdatacopy>1</doesdatacopy>\n          <fieldhelp></fieldhelp>\n          <audited>0</audited>\n          <num_lines>1</num_lines>\n          <maxlength>0</maxlength>\n          <append_only>0</append_only>\n          <allowHTML>0</allowHTML>\n        </field>\r\n        <field id="7" field_type="text" base_type="text">\r\n          <label>Description</label>\n          <nowrap>0</nowrap>\n          <bold>0</bold>\n          <required>0</required>\n          <appears_by_default>1</appears_by_default>\n          <find_enabled>1</find_enabled>\n          <allow_new_choices>0</allow_new_choices>\n          <sort_as_given>1</sort_as_given>\n          <carrychoices>1</carrychoices>\n          <foreignkey>0</foreignkey>\n          <unique>0</unique>\n          <doesdatacopy>1</doesdatacopy>\n          <fieldhelp></fieldhelp>\n          <audited>0</audited>\n          <num_lines>1</num_lines>\n          <maxlength>0</maxlength>\n          <append_only>0</append_only>\n          <allowHTML>0</allowHTML>\n        </field>\r\n        <field id="8" field_type="file" base_type="text">\r\n          <label>Document</label>\n          <nowrap>0</nowrap>\n          <bold>0</bold>\n          <required>0</required>\n          <appears_by_default>1</appears_by_default>\n          <find_enabled>0</find_enabled>\n          <allow_new_choices>0</allow_new_choices>\n          <sort_as_given>0</sort_as_given>\n          <carrychoices>1</carrychoices>\n          <foreignkey>0</foreignkey>\n          <unique>0</unique>\n          <doesdatacopy>0</doesdatacopy>\n          <fieldhelp></fieldhelp>\n          <audited>0</audited>\n          <max_versions>3</max_versions>\n          <see_versions>1</see_versions>\n          <open>1</open>\n          <use_new_window>1</use_new_window>\n        </field>\r\n      </fields>\r\n<lastluserid>22</lastluserid>\r\n      <records>\r\n        <record>\r\n          <f id="3">3</f>\r\n          <f id="6">Jinja Expression</f>\r\n          <f id="7">Jinja Expression</f>\r\n          <f id="8">sample_jinja.docx<url>https://bps.quickbase.com/up/bqsuve7qy/g/rd/ei/va/sample_jinja.docx</url></f>\r\n          <update_id>1600070111927</update_id>\r\n        </record>\r\n        <record>\r\n          <f id="3">2</f>\r\n          <f id="6">Sample Document</f>\r\n          <f id="7">Sample Document</f>\r\n          <f id="8">Sample Document.docx<url>https://bps.quickbase.com/up/bqsuve7qy/g/rc/ei/va/Sample%20Document.docx</url></f>\r\n          <update_id>1599466752412</update_id>\r\n        </record>\r\n      </records>\r\n    </table>\r\n</qdbapi>\r\n'

In [5]:
data1

{'qdbapi': {'action': 'API_DoQuery',
  'errcode': '0',
  'errtext': 'No error',
  'qid': '-1',
  'qname': None,
  'table': {'name': 'Track Record Documents',
   'original': {'table_id': 'bqsuve7qy',
    'app_id': 'bpqjjg28h',
    'cre_date': '1598351898050',
    'mod_date': '1599656949691',
    'next_record_id': '4',
    'next_field_id': '9',
    'next_query_id': '5',
    'def_sort_fid': '2',
    'def_sort_order': '0',
    'key_fid': '3',
    'single_record_name': 'Track Record Document',
    'plural_record_name': 'Track record documents'},
   'variables': {'var': [{'@name': 'appID', '#text': 'bpqjjg28h'},
     {'@name': 'SecretKey',
      '#text': 'cIYauNev61s.KYXLMcY9yATi9z9_OOTzlPp9LkVsYKA610syho2Yb4Y'},
     {'@name': 'tblUserPreferenceList', '#text': 'bpq27dt3d'}]},
   'queries': {'query': [{'@id': '1',
      'qyname': 'List All',
      'qytype': 'table',
      'qyopts': 'nos.qws.',
      'qycalst': '0.0'},
     {'@id': '2',
      'qyname': 'List Changes',
      'qytype': 'table',
      'qydesc': 'Sorted by Date Modified',
      'qyslst': '2',
      'qyopts': 'so-D.onlynew.nos.qws.',
      'qycalst': '0.0'}]},
   'fields': {'field': [{'@id': '3',
      '@field_type': 'recordid',
      '@base_type': 'int32',
      '@role': 'recordid',
      '@mode': 'virtual',
      'label': 'Record ID#',
      'nowrap': '1',
      'bold': '0',
      'required': '0',
      'appears_by_default': '1',
      'find_enabled': '0',
      'allow_new_choices': '0',
      'sort_as_given': '1',
      'carrychoices': '1',
      'foreignkey': '0',
      'unique': '1',
      'doesdatacopy': '0',
      'fieldhelp': None,
      'audited': '0',
      'decimal_places': '0',
      'comma_start': '4',
      'numberfmt': '0',
      'does_average': '0',
      'does_total': '0',
      'blank_is_zero': '1'},
     {'@id': '6',
      '@field_type': 'text',
      '@base_type': 'text',
      'label': 'Title',
      'nowrap': '0',
      'bold': '0',
      'required': '0',
      'appears_by_default': '1',
      'find_enabled': '1',
      'allow_new_choices': '0',
      'sort_as_given': '1',
      'carrychoices': '1',
      'foreignkey': '0',
      'unique': '0',
      'doesdatacopy': '1',
      'fieldhelp': None,
      'audited': '0',
      'num_lines': '1',
      'maxlength': '0',
      'append_only': '0',
      'allowHTML': '0'},
     {'@id': '7',
      '@field_type': 'text',
      '@base_type': 'text',
      'label': 'Description',
      'nowrap': '0',
      'bold': '0',
      'required': '0',
      'appears_by_default': '1',
      'find_enabled': '1',
      'allow_new_choices': '0',
      'sort_as_given': '1',
      'carrychoices': '1',
      'foreignkey': '0',
      'unique': '0',
      'doesdatacopy': '1',
      'fieldhelp': None,
      'audited': '0',
      'num_lines': '1',
      'maxlength': '0',
      'append_only': '0',
      'allowHTML': '0'},
     {'@id': '8',
      '@field_type': 'file',
      '@base_type': 'text',
      'label': 'Document',
      'nowrap': '0',
      'bold': '0',
      'required': '0',
      'appears_by_default': '1',
      'find_enabled': '0',
      'allow_new_choices': '0',
      'sort_as_given': '0',
      'carrychoices': '1',
      'foreignkey': '0',
      'unique': '0',
      'doesdatacopy': '0',
      'fieldhelp': None,
      'audited': '0',
      'max_versions': '3',
      'see_versions': '1',
      'open': '1',
      'use_new_window': '1'}]},
   'lastluserid': '22',
   'records': {'record': [{'f': [{'@id': '3', '#text': '3'},
       {'@id': '6', '#text': 'Jinja Expression'},
       {'@id': '7', '#text': 'Jinja Expression'},
       {'@id': '8',
        'url': 'https://bps.quickbase.com/up/bqsuve7qy/g/rd/ei/va/sample_jinja.docx',
        '#text': 'sample_jinja.docx'}],
      'update_id': '1600070111927'},
     {'f': [{'@id': '3', '#text': '2'},
       {'@id': '6', '#text': 'Sample Document'},
       {'@id': '7', '#text': 'Sample Document'},
       {'@id': '8',
        'url': 'https://bps.quickbase.com/up/bqsuve7qy/g/rc/ei/va/Sample%20Document.docx',
        '#text': 'Sample Document.docx'}],
      'update_id': '1599466752412'}]}}}}

In [6]:
# def get_data(Title):
#     Record Id=Title=Description=Document URL=""
#     for i in data1.values():
#             values=i['table']['records']['record']['f']
#             print(values)
#             for id_item in values:
#                 if id_item["@id"]=="6":
#                     Title=id_item['#text']
#                     print(Title)
#                 if id_item["@id"]=="7":
#                     Description=id_item['#text']
#                     print(Description)
#                 if id_item["@id"]=="8":
#                     Document=id_item['#text']
#             #return {"Title":Title,"Description":Description,"Document":Document}
#                     doc_data={"Document":Document }
#             return doc_data

In [7]:
document_url=[]
R_ID=[]
def get_data():
    document_url=[]
    R_ID=[]
    R_Id=Document=""
    for i in data1.values():
        values=i['table']['records']['record']
        for j in values:
            list_data=j['f']
#             print(list_data)
            for data in list_data:
                if data['@id']=="8":
                    Document=data['url']
                    document_url.append(Document)
                if data['@id']=="3":
                    R_Id=data['#text']
                    R_ID.append(R_Id)
#     print(R_ID)
#     print(document_url)
    Mapped_data=dict(zip(R_ID,document_url))
    return Mapped_data
#             latest={"Document":Document,"R_Id":R_Id}
#             latest=dict(zip(Document,R_Id))
#             print(latest)
#                 doc_data={R_id:Document}

In [8]:
data_all=get_data()

In [9]:
data_all

{'3': 'https://bps.quickbase.com/up/bqsuve7qy/g/rd/ei/va/sample_jinja.docx',
 '2': 'https://bps.quickbase.com/up/bqsuve7qy/g/rc/ei/va/Sample%20Document.docx'}

In [10]:
from zipfile import ZipFile
from urllib.request import urlopen
from io import BytesIO
from zipfile import *
from bs4 import BeautifulSoup
import pandas as pd

In [11]:
for key, value in data_all.items():
    print(value)
#     wordfile=urlopen(value).read()
#     print(wordfile)

https://bps.quickbase.com/up/bqsuve7qy/g/rd/ei/va/sample_jinja.docx
https://bps.quickbase.com/up/bqsuve7qy/g/rc/ei/va/Sample%20Document.docx

In [12]:
track_changed_for_del=[]
track_changed_for_ins=[]
for key, value in data_all.items():
    wordfile=urlopen(value).read()
    wordfile=BytesIO(wordfile)
    document=ZipFile(wordfile)
    document.namelist()
    xml_content=document.read('word/document.xml')
    wordobj=BeautifulSoup(xml_content.decode('utf-8'),'xml')
    key_record=key
    for dl in wordobj.find_all('w:del'):
        Text=dl.text
        author=dl.get('w:author')
        Date=dl.get('w:date')
        Type='Deleted Text'
        ID=dl.get('w:id')
        ID=int(ID)
        dataDict_del = { 'Text':Text,'Author':author,'Date':Date,'Type':Type,'ID':ID,'Record_Id':key_record}
        track_changed_for_del.append(dataDict_del)
    
        
    for ins in wordobj.find_all('w:ins'):
        Text=ins.text
        author=ins.get('w:author')
        Date=ins.get('w:date')
        Type='Inserted Text'
        ID=ins.get('w:id')
        ID=int(ID)
        dataDict_ins = { 'Text':Text,'Author':author,'Date':Date,'Type':Type,'ID':ID,'Record_Id':key_record}
        track_changed_for_ins.append(dataDict_ins)
    df_track_changed_ins= pd.DataFrame(track_changed_for_ins)
    df_track_changed_del= pd.DataFrame(track_changed_for_del)
    df_track_changed_del["Text"]= df_track_changed_del["Text"].replace(' ', "NaN")
    df_track_changed_ins["Text"]= df_track_changed_ins["Text"].replace('', "NaN")
    df_track_changed_del.drop(df_track_changed_del.loc[df_track_changed_del['Text']=='NaN'].index, inplace=True)
    df_track_changed_ins=df_track_changed_ins.sort_values(by='ID')
    df_track_changed_del=df_track_changed_del.sort_values(by='ID')

In [13]:
type(track_changed_for_ins)

list

In [14]:
df_track_changed_ins

,Text,Author,Date,Type,ID,Record_Id
0,template file,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Inserted Text,0,3
5,Dinesh,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,0,2
6,vijayakumar,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,1,2
1,librarry,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,3,3
7,NaN,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,3,2
8,Asasaafas,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,4,2
2,XML,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,5,3
9,safsafsf,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,5,2
10,ACCENTURE,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,7,2
3,.html,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,8,3
11,Abcde xyzdgh sdgfdslkdfs dsvjsdgj;a,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,8,2
4,jinja,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,9,3

In [15]:
df_track_changed_del

,Text,Author,Date,Type,ID,Record_Id
0,templating,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Deleted Text,1,3
2,file,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Deleted Text,4,3
3,"LaTeX,","Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,6,3
6,Company,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Deleted Text,6,2
4,template,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,7,3
5,jinja2,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,11,3

In [16]:
all_data=df_track_changed_ins.append(df_track_changed_del)

In [17]:
all_data=all_data.sort_values(by='ID',ascending=True)

In [18]:
all_data

,Text,Author,Date,Type,ID,Record_Id
0,template file,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Inserted Text,0,3
5,Dinesh,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,0,2
6,vijayakumar,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,1,2
0,templating,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Deleted Text,1,3
1,librarry,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,3,3
7,NaN,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,3,2
8,Asasaafas,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,4,2
2,file,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Deleted Text,4,3
2,XML,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,5,3
9,safsafsf,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,5,2
6,Company,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Deleted Text,6,2
3,"LaTeX,","Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,6,3
10,ACCENTURE,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,7,2
4,template,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,7,3
11,Abcde xyzdgh sdgfdslkdfs dsvjsdgj;a,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,8,2
3,.html,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,8,3
4,jinja,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,9,3
5,jinja2,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,11,3

In [19]:
val=all_data.to_dict('records')

In [20]:
val

[{'Text': 'template file',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:23:00Z',
  'Type': 'Inserted Text',
  'ID': 0,
  'Record_Id': '3'},
 {'Text': 'Dinesh',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:11:00Z',
  'Type': 'Inserted Text',
  'ID': 0,
  'Record_Id': '2'},
 {'Text': 'vijayakumar',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:11:00Z',
  'Type': 'Inserted Text',
  'ID': 1,
  'Record_Id': '2'},
 {'Text': 'templating',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:23:00Z',
  'Type': 'Deleted Text',
  'ID': 1,
  'Record_Id': '3'},
 {'Text': ' librarry',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 3,
  'Record_Id': '3'},
 {'Text': 'NaN',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 3,
  'Record_Id': '2'},
 {'Text': 'Asasaafas',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 4,
  'Record_Id': '2'},
 {'Text': 'file',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:23:00Z',
  'Type': 'Deleted Text',
  'ID': 4,
  'Record_Id': '3'},
 {'Text': 'XML',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 5,
  'Record_Id': '3'},
 {'Text': 'safsafsf',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 5,
  'Record_Id': '2'},
 {'Text': 'Company',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Deleted Text',
  'ID': 6,
  'Record_Id': '2'},
 {'Text': 'LaTeX,',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Deleted Text',
  'ID': 6,
  'Record_Id': '3'},
 {'Text': 'ACCENTURE',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 7,
  'Record_Id': '2'},
 {'Text': 'template',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Deleted Text',
  'ID': 7,
  'Record_Id': '3'},
 {'Text': 'Abcde xyzdgh sdgfdslkdfs dsvjsdgj;a',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:11:00Z',
  'Type': 'Inserted Text',
  'ID': 8,
  'Record_Id': '2'},
 {'Text': '.html',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 8,
  'Record_Id': '3'},
 {'Text': 'jinja',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 9,
  'Record_Id': '3'},
 {'Text': 'jinja2',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Deleted Text',
  'ID': 11,
  'Record_Id': '3'}]

In [21]:
val

[{'Text': 'template file',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:23:00Z',
  'Type': 'Inserted Text',
  'ID': 0,
  'Record_Id': '3'},
 {'Text': 'Dinesh',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:11:00Z',
  'Type': 'Inserted Text',
  'ID': 0,
  'Record_Id': '2'},
 {'Text': 'vijayakumar',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:11:00Z',
  'Type': 'Inserted Text',
  'ID': 1,
  'Record_Id': '2'},
 {'Text': 'templating',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:23:00Z',
  'Type': 'Deleted Text',
  'ID': 1,
  'Record_Id': '3'},
 {'Text': ' librarry',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 3,
  'Record_Id': '3'},
 {'Text': 'NaN',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 3,
  'Record_Id': '2'},
 {'Text': 'Asasaafas',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 4,
  'Record_Id': '2'},
 {'Text': 'file',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:23:00Z',
  'Type': 'Deleted Text',
  'ID': 4,
  'Record_Id': '3'},
 {'Text': 'XML',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 5,
  'Record_Id': '3'},
 {'Text': 'safsafsf',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 5,
  'Record_Id': '2'},
 {'Text': 'Company',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Deleted Text',
  'ID': 6,
  'Record_Id': '2'},
 {'Text': 'LaTeX,',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Deleted Text',
  'ID': 6,
  'Record_Id': '3'},
 {'Text': 'ACCENTURE',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:13:00Z',
  'Type': 'Inserted Text',
  'ID': 7,
  'Record_Id': '2'},
 {'Text': 'template',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Deleted Text',
  'ID': 7,
  'Record_Id': '3'},
 {'Text': 'Abcde xyzdgh sdgfdslkdfs dsvjsdgj;a',
  'Author': 'Vijayakumar, Dinesh',
  'Date': '2020-04-13T16:11:00Z',
  'Type': 'Inserted Text',
  'ID': 8,
  'Record_Id': '2'},
 {'Text': '.html',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 8,
  'Record_Id': '3'},
 {'Text': 'jinja',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Inserted Text',
  'ID': 9,
  'Record_Id': '3'},
 {'Text': 'jinja2',
  'Author': 'Sitaram Verma, Preeti',
  'Date': '2020-09-14T13:24:00Z',
  'Type': 'Deleted Text',
  'ID': 11,
  'Record_Id': '3'}]

In [23]:
csv_data=all_data.to_csv(index=False,header=False)

In [32]:
csv_data

'template file,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Inserted Text,0,3\r\nDinesh,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,0,2\r\nvijayakumar,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,1,2\r\ntemplating,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Deleted Text,1,3\r\n librarry,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,3,3\r\nNaN,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,3,2\r\nAsasaafas,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,4,2\r\nfile,"Sitaram Verma, Preeti",2020-09-14T13:23:00Z,Deleted Text,4,3\r\nXML,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,5,3\r\nsafsafsf,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,5,2\r\nCompany,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Deleted Text,6,2\r\n"LaTeX,","Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,6,3\r\nACCENTURE,"Vijayakumar, Dinesh",2020-04-13T16:13:00Z,Inserted Text,7,2\r\ntemplate,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,7,3\r\nAbcde xyzdgh sdgfdslkdfs dsvjsdgj;a,"Vijayakumar, Dinesh",2020-04-13T16:11:00Z,Inserted Text,8,2\r\n.html,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,8,3\r\njinja,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Inserted Text,9,3\r\njinja2,"Sitaram Verma, Preeti",2020-09-14T13:24:00Z,Deleted Text,11,3\r\n'

In [38]:
usertoken = 'b5d3bm_kn5b_d4c4hh5b76ajm4t6fzg96bbber'
dbid = 'bqi9wpaun'

In [39]:
field_list='12.6.8.7.11.13'

In [40]:
headers = {'Content-Type': 'application/xml', 'QUICKBASE-ACTION': 'api_importfromcsv'}
data = '<qdbapi><records_csv><![CDATA[' + csv_data + ']]></records_csv><clist>'+field_list+'</clist>\
        <usertoken>' + usertoken + '</usertoken></qdbapi>'

In [41]:
import requests
r2 = requests.post(url='https://bps.quickbase.com/db/' + dbid, data=data.encode('utf-8'), headers=headers)

r2

In [37]:
print(r2)

<Response [200]>

In [53]:
data_test = r2.text

In [51]:
data_test

'<?xml version="1.0" ?>\r\n<qdbapi>\n\t<action>api_importfromcsv</action>\r\n\t<errcode>1</errcode>\r\n\t<errtext>Unknown error</errtext>\r\n\t<errdetail>Some record IDs specified were not found in the table.</errdetail>\r\n\t<num_recs_input>18</num_recs_input>\r\n\t<num_recs_added>0</num_recs_added>\r\n\t<num_recs_updated>0</num_recs_updated>\r\n\t<num_recs_unchanged>0</num_recs_unchanged>\r\n</qdbapi>\r\n'